# Generated by Django 3.1.5 on 2021-01-21 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Performer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name')),
                ('url', models.URLField()),
                ('gender', models.CharField(choices=[('M', 'MALE'), ('F', 'FEMALE'), ('TM', 'TRANS_M'), ('TF', 'TRANS_F'), ('IS', 'INTERSEX')], default='F', max_length=8)),
                ('aliases', models.CharField(max_length=150, verbose_name='aliases')),
                ('favorite', models.BooleanField(default=False)),
            ],
        ),
    ]
